plugins {
    id 'java'
    id 'application'
}

group = 'ru.shift'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ru.shift.app.Application'
}

java {
    sourceCompatibility = '21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.code.gson:gson:2.11.0")
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'ch.qos.logback:logback-classic:1.5.33'
}